apiVersion: v1
kind: Service
metadata:
  name: express-frontend
spec:
  selector:
    app: express-frontend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: NodePort        # exposes app on minikube IP so you can open in browser
